In [1]:
import requests
import json
import pandas as pd
import numpy as np
from datetime import datetime
import time
import numpy as np

In [2]:
def format_data(df, ticker):
    renamed_columns = {
    "Fecha": 'Date', 
    'Último': f'{ticker}-Close', 
    "Apertura": f'{ticker}-Open', 
    "Máximo": f"{ticker}-High", 
    "Mínimo": f"{ticker}-Low", 
    "Vol.": f"{ticker}-Volume", 
    "% var.": f"{ticker}-% var"
    }
    df = df.rename(columns=renamed_columns)
    df["Date"] = pd.to_datetime(df["Date"], format="%d.%m.%Y")
    return df

# OHLC (Open - High - Low - Close) del bitcoin
**Open** -> Precio de apertura

**High** -> Precio máximo

**Low** -> Precio mínimo

**Close** -> Precio de cierre

**Volume** -> Cantidad de BTC que se movieron

In [3]:
startTime = 1502928000000
limit = time.time() * 1000

OHLC_dataframes = []

while (startTime < limit):
    url = 'https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=1d&limit=1000&startTime={startTime}'.format(startTime=startTime)
    res = requests.get(url)
    data = json.loads(res.text)
    df = pd.DataFrame(data, columns=[
        "Open time", "Open", "High", "Low", "Close", "Volume",
        "Close time", "Quote asset volume", "Number of trades",
        "Taker buy base asset volume", "Taker buy quote asset volume", "Ignore"
    ])
    df["Date"] = pd.to_datetime(df["Open time"], unit='ms') - pd.Timedelta(days=1)
    startTime = df['Close time'].iloc[-1]
    df = df[["Date", "Open", "High", "Low", "Close", "Volume"]]
    df[["Open", "High", "Low", "Close", "Volume"]] = df[["Open", "High", "Low", "Close", "Volume"]].astype(float)
    OHLC_dataframes.append(df)
    
OHLC_data = pd.concat(df for df in OHLC_dataframes)
OHLC_data

          Date       Open       High        Low      Close        Volume
0   2017-08-16    4261.48    4485.39    4200.74    4285.08    795.150377
1   2017-08-17    4285.08    4371.52    3938.77    4108.37   1199.888264
2   2017-08-18    4108.37    4184.69    3850.00    4139.98    381.309763
3   2017-08-19    4120.98    4211.08    4032.62    4086.29    467.083022
4   2017-08-20    4069.13    4119.62    3911.79    4016.00    691.743060
..         ...        ...        ...        ...        ...           ...
948 2025-09-11  115482.69  116665.63  114740.99  116029.42  15324.107190
949 2025-09-12  116029.41  116298.78  115127.27  115918.29   8269.403940
950 2025-09-13  115918.29  116165.19  115135.00  115268.01   6707.601970
951 2025-09-14  115268.01  116757.99  114384.00  115349.71  13212.511490
952 2025-09-15  115349.71  116009.62  114737.11  115172.16   5830.330060

[2953 rows x 6 columns]

# OHLC del petróleo (WTI) desde la fecha más vieja en la que pudimos obtener datos del BTC
https://es.investing.com/commodities/crude-oil-historical-data

In [4]:
OHLC_WTI = pd.read_csv("CSVs/WTI to 15.9.2025.csv")
OHLC_WTI = format_data(OHLC_WTI, "WTI")

for feature in OHLC_WTI.columns.values[1:-2]:
    OHLC_WTI[feature] = OHLC_WTI[feature].str.replace(",",".")
OHLC_WTI[["WTI-Close", "WTI-Open", "WTI-High", "WTI-Low"]] = OHLC_WTI[["WTI-Close", "WTI-Open", "WTI-High", "WTI-Low"]].astype(float)

hay_sin_k = OHLC_WTI["WTI-Volume"].str.endswith("K", na=False).all()
if hay_sin_k:
    print("✅ Todos los valores terminan en K")
else:
    print("⚠️ Hay valores que NO terminan en K")

OHLC_WTI.head(25)

⚠️ Hay valores que NO terminan en K

         Date  WTI-Close  WTI-Open  WTI-High  WTI-Low WTI-Volume WTI-% var
0  2025-09-15      63.04     62.40     63.24    62.39     32,61K     0,57%
1  2025-09-14      62.68     62.32     62.71    62.26      2,50K    -0,02%
2  2025-09-12      62.69     62.27     63.98    61.69    281,94K     0,51%
3  2025-09-11      62.37     63.80     63.80    62.21    222,66K    -2,04%
4  2025-09-10      63.67     62.74     64.08    62.72    260,68K     1,66%
5  2025-09-09      62.63     62.43     63.67    62.37    268,53K     0,59%
6  2025-09-08      62.26     62.00     63.34    61.85    237,29K     0,05%
7  2025-09-07      62.23     62.34     62.34    61.87      6,62K     0,58%
8  2025-09-05      61.87     63.33     63.49    61.45    294,54K    -2,54%
9  2025-09-04      63.48     63.82     63.84    62.72    251,69K    -0,77%
10 2025-09-03      63.97     65.62     65.72    63.72    298,74K    -2,47%
11 2025-09-02      65.59     63.95     66.03    63.66    320,22K     1,47%
12 2025-09-01      64.64     64.61     64.88    63.67     60,13K     1,06%
13 2025-08-31      63.96     63.98     64.01    63.92        NaN    -0,08%
14 2025-08-29      64.01     64.26     64.55    63.88    183,26K    -0,91%
15 2025-08-28      64.60     63.87     64.70    63.35    208,93K     0,70%
16 2025-08-27      64.15     63.31     64.23    62.95    193,48K     1,42%
17 2025-08-26      63.25     64.75     64.76    63.13    199,10K    -2,39%
18 2025-08-25      64.80     63.88     65.10    63.53    185,27K     1,79%
19 2025-08-22      63.66     63.50     63.93    63.31    223,17K     0,22%
20 2025-08-21      63.52     62.85     63.67    62.52    250,17K     0,49%
21 2025-08-20      63.21     62.60     63.55    62.39     27,16K     1,38%
22 2025-08-19      62.35     63.27     63.39    62.25     99,48K    -1,69%
23 2025-08-18      63.42     63.00     63.79    62.18     95,11K     0,99%
24 2025-08-15      62.80     63.91     64.15    62.68    197,39K    -1,81%

In [5]:
print("NaN en la columna WTI-Volume:")
print(OHLC_WTI["WTI-Volume"].isna().sum())
print(OHLC_WTI[OHLC_WTI["WTI-Volume"].isna()])
print("Valores en la columna WTI-Volume sin una K")
filtro = OHLC_WTI["WTI-Volume"].notna() & ~OHLC_WTI["WTI-Volume"].str.endswith("K", na=False)
print(filtro.sum())
print(OHLC_WTI[filtro])

NaN en la columna WTI-Volume:
88
           Date  WTI-Close  WTI-Open  WTI-High  WTI-Low WTI-Volume WTI-% var
13   2025-08-31      63.96     63.98     64.01    63.92        NaN    -0,08%
84   2025-05-25      61.93     61.73     62.15    61.58        NaN     0,65%
268  2024-09-02      73.78     73.00     74.39    72.89        NaN     1,10%
269  2024-09-01      72.98     73.33     73.42    72.97        NaN     0,45%
311  2024-07-04      83.94     83.61     84.20    83.03        NaN     1,11%
...         ...        ...       ...       ...      ...        ...       ...
2027 2018-01-01      60.24     60.26     60.28    60.15        NaN    -0,33%
2032 2017-12-25      58.59     58.41     58.62    58.38        NaN     0,09%
2054 2017-11-23      58.38     57.97     58.58    57.76        NaN     0,62%
2112 2017-09-04      47.41     47.31     47.66    47.16        NaN     0,19%
2113 2017-09-03      47.32     47.31     47.42    47.30        NaN     0,06%

[88 rows x 7 columns]
Valores en la columna WTI-Volume sin una K
6
           Date  WTI-Close  WTI-Open  WTI-High  WTI-Low WTI-Volume WTI-% var
1419 2020-04-21      11.57     21.32     22.58     6.50      2,29M   -43,37%
1420 2020-04-20      20.43     24.76     24.92    20.19      1,32M   -18,38%
1440 2020-03-20      22.63     25.59     28.49    22.39      1,13M   -12,66%
1441 2020-03-19      25.91     22.82     28.28    21.77      1,19M    24,39%
1442 2020-03-18      20.83     27.30     27.60    20.52      1,00M   -23,78%
2111 2017-09-05      48.66     47.28     48.98    47.15      1,03M     2,64%

In [6]:
def parse_value(x):
    if pd.isna(x):  # mantenemos los NaN por ahora
        return np.nan
    x = str(x).strip()
    
    factor = 1
    if x.endswith("K"):
        factor = 1000
        x = x[:-1]
    elif x.endswith("M"):
        factor = 1000000
        x = x[:-1]
    
    # reemplazamos coma decimal por punto
    x = x.replace(",", ".")
    
    try:
        return float(x) * factor
    except ValueError:
        return np.nan  # en caso de algún valor raro

OHLC_WTI["WTI-Volume"] = OHLC_WTI["WTI-Volume"].apply(parse_value)
OHLC_WTI[OHLC_WTI["WTI-Volume"] >= 1000000]

           Date  WTI-Close  WTI-Open  WTI-High  WTI-Low  WTI-Volume WTI-% var
1419 2020-04-21      11.57     21.32     22.58     6.50   2290000.0   -43,37%
1420 2020-04-20      20.43     24.76     24.92    20.19   1320000.0   -18,38%
1440 2020-03-20      22.63     25.59     28.49    22.39   1130000.0   -12,66%
1441 2020-03-19      25.91     22.82     28.28    21.77   1190000.0    24,39%
1442 2020-03-18      20.83     27.30     27.60    20.52   1000000.0   -23,78%
2111 2017-09-05      48.66     47.28     48.98    47.15   1030000.0     2,64%

In [7]:
OHLC_WTI.head(25)

         Date  WTI-Close  WTI-Open  WTI-High  WTI-Low  WTI-Volume WTI-% var
0  2025-09-15      63.04     62.40     63.24    62.39     32610.0     0,57%
1  2025-09-14      62.68     62.32     62.71    62.26      2500.0    -0,02%
2  2025-09-12      62.69     62.27     63.98    61.69    281940.0     0,51%
3  2025-09-11      62.37     63.80     63.80    62.21    222660.0    -2,04%
4  2025-09-10      63.67     62.74     64.08    62.72    260680.0     1,66%
5  2025-09-09      62.63     62.43     63.67    62.37    268530.0     0,59%
6  2025-09-08      62.26     62.00     63.34    61.85    237290.0     0,05%
7  2025-09-07      62.23     62.34     62.34    61.87      6620.0     0,58%
8  2025-09-05      61.87     63.33     63.49    61.45    294540.0    -2,54%
9  2025-09-04      63.48     63.82     63.84    62.72    251690.0    -0,77%
10 2025-09-03      63.97     65.62     65.72    63.72    298740.0    -2,47%
11 2025-09-02      65.59     63.95     66.03    63.66    320220.0     1,47%
12 2025-09-01      64.64     64.61     64.88    63.67     60130.0     1,06%
13 2025-08-31      63.96     63.98     64.01    63.92         NaN    -0,08%
14 2025-08-29      64.01     64.26     64.55    63.88    183260.0    -0,91%
15 2025-08-28      64.60     63.87     64.70    63.35    208930.0     0,70%
16 2025-08-27      64.15     63.31     64.23    62.95    193480.0     1,42%
17 2025-08-26      63.25     64.75     64.76    63.13    199100.0    -2,39%
18 2025-08-25      64.80     63.88     65.10    63.53    185270.0     1,79%
19 2025-08-22      63.66     63.50     63.93    63.31    223170.0     0,22%
20 2025-08-21      63.52     62.85     63.67    62.52    250170.0     0,49%
21 2025-08-20      63.21     62.60     63.55    62.39     27160.0     1,38%
22 2025-08-19      62.35     63.27     63.39    62.25     99480.0    -1,69%
23 2025-08-18      63.42     63.00     63.79    62.18     95110.0     0,99%
24 2025-08-15      62.80     63.91     64.15    62.68    197390.0    -1,81%

# OHLC del petróleo (Brent) desde la fecha más vieja en la que pudimos obtener datos del BTC
https://es.investing.com/commodities/brent-oil-historical-data

In [8]:
OHLC_BRENT = pd.read_csv("CSVs/Brent to 15.9.2025.csv")
OHLC_BRENT = format_data(OHLC_BRENT, "BRENT")

for feature in OHLC_BRENT.columns.values[1:-2]:
    OHLC_BRENT[feature] = OHLC_BRENT[feature].str.replace(",",".")
OHLC_BRENT[["BRENT-Close", "BRENT-Open", "BRENT-High", "BRENT-Low"]] = OHLC_BRENT[["BRENT-Close", "BRENT-Open", "BRENT-High", "BRENT-Low"]].astype(float)

hay_sin_k = OHLC_BRENT["BRENT-Volume"].str.endswith("K", na=False).all()
if hay_sin_k:
    print("✅ Todos los valores terminan en K")
else:
    print("⚠️ Hay valores que NO terminan en K")

OHLC_BRENT.head(25)

⚠️ Hay valores que NO terminan en K

,Date,BRENT-Close,BRENT-Open,BRENT-High,BRENT-Low,BRENT-Volume,BRENT-% var
0,2025-09-15,67.51,66.91,67.55,66.90,"108,61K","0,91%"
1,2025-09-14,66.90,67.17,67.17,66.78,"2,21K","-0,13%"
2,2025-09-12,66.99,66.24,68.17,65.71,"397,41K","0,93%"
3,2025-09-11,66.37,67.58,67.62,66.15,"247,54K","-1,66%"
4,2025-09-10,67.49,66.69,67.78,66.66,"274,93K","1,66%"
5,2025-09-09,66.39,66.23,67.38,66.12,"309,16K","0,56%"
6,2025-09-08,66.02,65.55,67.04,65.51,"257,32K","0,79%"
7,2025-09-05,65.50,66.82,67.05,65.07,"327,79K","-2,22%"
8,2025-09-04,66.99,67.41,67.41,66.35,"295,61K","-0,90%"
9,2025-09-03,67.60,69.10,69.24,67.36,"393,06K","-2,23%"
10,2025-09-02,69.14,68.19,69.53,68.05,"346,06K","1,45%"
11,2025-09-01,68.15,67.42,68.36,67.12,"151,21K","0,04%"
12,2025-08-29,68.12,68.24,68.39,67.90,"18,13K","-0,73%"
13,2025-08-28,68.62,67.71,68.71,67.39,"105,36K","0,84%"
14,2025-08-27,68.05,67.39,68.12,66.91,"131,60K","1,23%"
15,2025-08-26,67.22,68.73,68.73,67.11,"177,90K","-2,30%"
16,2025-08-25,68.80,67.89,69.07,67.57,"130,69K","2,35%"
17,2025-08-22,67.22,67.05,67.45,66.89,"276,32K","0,15%"
18,2025-08-21,67.12,66.46,67.25,66.25,"275,96K","1,22%"
19,2025-08-20,66.31,65.59,66.54,65.31,"263,66K","1,55%"
20,2025-08-19,65.30,65.98,66.01,65.14,"200,65K","-1,08%"
21,2025-08-18,66.01,65.26,66.24,64.79,"195,57K","0,24%"
22,2025-08-15,65.85,66.87,67.06,65.73,"251,20K","-1,48%"
23,2025-08-14,66.84,65.76,66.99,65.55,"275,02K","1,84%"
24,2025-08-13,65.63,66.14,66.33,65.01,"310,06K","-0,74%"

In [9]:
print("NaN en la columna BRENT-Volume:")
print(OHLC_BRENT["BRENT-Volume"].isna().sum())
print("Valores en la columna BRENT-Volume sin una K")
filtro = ~OHLC_BRENT["BRENT-Volume"].str.endswith("K", na=False)
print(filtro.sum())
print(OHLC_BRENT[filtro])

NaN en la columna BRENT-Volume:
0
Valores en la columna BRENT-Volume sin una K
1
         Date  BRENT-Close  BRENT-Open  BRENT-High  BRENT-Low BRENT-Volume  \
67 2025-06-13        74.23        70.5        78.5      70.41        1,24M

   BRENT-% var
67       7,02%

In [10]:
OHLC_BRENT["BRENT-Volume"] = OHLC_BRENT["BRENT-Volume"].apply(parse_value)
OHLC_BRENT[OHLC_BRENT["BRENT-Volume"] >= 1000000]

,Date,BRENT-Close,BRENT-Open,BRENT-High,BRENT-Low,BRENT-Volume,BRENT-% var
67,2025-06-13,74.23,70.5,78.5,70.41,1240000.0,"7,02%"

In [11]:
OHLC_BRENT.head(25)

,Date,BRENT-Close,BRENT-Open,BRENT-High,BRENT-Low,BRENT-Volume,BRENT-% var
0,2025-09-15,67.51,66.91,67.55,66.90,108610.0,"0,91%"
1,2025-09-14,66.90,67.17,67.17,66.78,2210.0,"-0,13%"
2,2025-09-12,66.99,66.24,68.17,65.71,397410.0,"0,93%"
3,2025-09-11,66.37,67.58,67.62,66.15,247540.0,"-1,66%"
4,2025-09-10,67.49,66.69,67.78,66.66,274930.0,"1,66%"
5,2025-09-09,66.39,66.23,67.38,66.12,309160.0,"0,56%"
6,2025-09-08,66.02,65.55,67.04,65.51,257320.0,"0,79%"
7,2025-09-05,65.50,66.82,67.05,65.07,327790.0,"-2,22%"
8,2025-09-04,66.99,67.41,67.41,66.35,295610.0,"-0,90%"
9,2025-09-03,67.60,69.10,69.24,67.36,393060.0,"-2,23%"
10,2025-09-02,69.14,68.19,69.53,68.05,346060.0,"1,45%"
11,2025-09-01,68.15,67.42,68.36,67.12,151210.0,"0,04%"
12,2025-08-29,68.12,68.24,68.39,67.90,18130.0,"-0,73%"
13,2025-08-28,68.62,67.71,68.71,67.39,105360.0,"0,84%"
14,2025-08-27,68.05,67.39,68.12,66.91,131600.0,"1,23%"
15,2025-08-26,67.22,68.73,68.73,67.11,177900.0,"-2,30%"
16,2025-08-25,68.80,67.89,69.07,67.57,130690.0,"2,35%"
17,2025-08-22,67.22,67.05,67.45,66.89,276320.0,"0,15%"
18,2025-08-21,67.12,66.46,67.25,66.25,275960.0,"1,22%"
19,2025-08-20,66.31,65.59,66.54,65.31,263660.0,"1,55%"
20,2025-08-19,65.30,65.98,66.01,65.14,200650.0,"-1,08%"
21,2025-08-18,66.01,65.26,66.24,64.79,195570.0,"0,24%"
22,2025-08-15,65.85,66.87,67.06,65.73,251200.0,"-1,48%"
23,2025-08-14,66.84,65.76,66.99,65.55,275020.0,"1,84%"
24,2025-08-13,65.63,66.14,66.33,65.01,310060.0,"-0,74%"

# OHLC del SPX (ticker del S&P 500) desde la fecha más vieja en la que pudimos obtener datos del BTC
https://es.investing.com/indices/us-spx-500-historical-data

In [12]:
OHLC_SPX = pd.read_csv("CSVs/SPX to 16.9.2025.csv")
OHLC_SPX = format_data(OHLC_SPX, "SPX")

OHLC_SPX = OHLC_SPX[['Date', 'SPX-Close', 'SPX-Open', 'SPX-High', 'SPX-Low', 'SPX-% var']]
for feature in OHLC_SPX.columns.values[1:-1]:
    OHLC_SPX[feature] = OHLC_SPX[feature].str.replace(".","")
    OHLC_SPX[feature] = OHLC_SPX[feature].str.replace(",",".")
OHLC_SPX

           Date SPX-Close SPX-Open SPX-High  SPX-Low SPX-% var
0    2025-09-15   6615.28  6603.49  6619.62  6602.07     0,47%
1    2025-09-12   6584.29  6590.66  6600.21  6579.49    -0,05%
2    2025-09-11   6587.47  6554.41  6592.89  6545.80     0,85%
3    2025-09-10   6532.04  6550.29  6555.97  6516.34     0,30%
4    2025-09-09   6512.61  6503.33  6518.23  6483.08     0,27%
...         ...       ...      ...      ...      ...       ...
2026 2017-08-22   2452.50  2433.80  2454.80  2433.70     0,99%
2027 2017-08-21   2428.40  2425.50  2430.60  2417.30     0,12%
2028 2017-08-18   2425.60  2427.60  2440.30  2420.70    -0,18%
2029 2017-08-17   2430.00  2462.90  2465.00  2430.00    -1,54%
2030 2017-08-16   2468.10  2468.60  2474.90  2463.90     0,14%

[2031 rows x 6 columns]

In [13]:
OHLC_SPX[["SPX-Close", "SPX-Open", "SPX-High", "SPX-Low"]] = OHLC_SPX[["SPX-Close", "SPX-Open", "SPX-High", "SPX-Low"]].astype(float)
OHLC_SPX.dtypes

Date         datetime64[ns]
SPX-Close           float64
SPX-Open            float64
SPX-High            float64
SPX-Low             float64
SPX-% var            object
dtype: object

In [14]:
OHLC_SPX

           Date  SPX-Close  SPX-Open  SPX-High  SPX-Low SPX-% var
0    2025-09-15    6615.28   6603.49   6619.62  6602.07     0,47%
1    2025-09-12    6584.29   6590.66   6600.21  6579.49    -0,05%
2    2025-09-11    6587.47   6554.41   6592.89  6545.80     0,85%
3    2025-09-10    6532.04   6550.29   6555.97  6516.34     0,30%
4    2025-09-09    6512.61   6503.33   6518.23  6483.08     0,27%
...         ...        ...       ...       ...      ...       ...
2026 2017-08-22    2452.50   2433.80   2454.80  2433.70     0,99%
2027 2017-08-21    2428.40   2425.50   2430.60  2417.30     0,12%
2028 2017-08-18    2425.60   2427.60   2440.30  2420.70    -0,18%
2029 2017-08-17    2430.00   2462.90   2465.00  2430.00    -1,54%
2030 2017-08-16    2468.10   2468.60   2474.90  2463.90     0,14%

[2031 rows x 6 columns]

# OHLC del XAU/USD (precio del oro en USD) desde la fecha más vieja en la que pudimos obtener datos del BTC
https://es.investing.com/currencies/xau-usd-historical-data

In [15]:
OHLC_XAUUSD = pd.read_csv("CSVs/XAU-USD to 16.9.2025.csv")
OHLC_XAUUSD = format_data(OHLC_XAUUSD, "XAUUSD")

OHLC_XAUUSD = OHLC_XAUUSD[['Date', 'XAUUSD-Close', 'XAUUSD-Open', 'XAUUSD-High', 'XAUUSD-Low', 'XAUUSD-% var']]
for feature in OHLC_XAUUSD.columns.values[1:-1]:
    OHLC_XAUUSD[feature] = OHLC_XAUUSD[feature].str.replace(".","")
    OHLC_XAUUSD[feature] = OHLC_XAUUSD[feature].str.replace(",",".")
OHLC_XAUUSD

           Date XAUUSD-Close XAUUSD-Open XAUUSD-High XAUUSD-Low XAUUSD-% var
0    2025-09-16      3694.63     3677.29     3699.57    3674.79        0,48%
1    2025-09-15      3676.97     3644.40     3685.65    3626.60        1,06%
2    2025-09-14      3638.26     3644.79     3646.19    3636.92       -0,13%
3    2025-09-12      3643.13     3635.01     3656.86    3630.48        0,25%
4    2025-09-11      3634.09     3642.60     3649.27    3614.01       -0,18%
...         ...          ...         ...         ...        ...          ...
2098 2017-08-22      1284.72     1291.18     1292.69    1282.11       -0,50%
2099 2017-08-21      1291.22     1283.60     1293.58    1280.60        0,52%
2100 2017-08-18      1284.50     1288.20     1301.20    1283.64       -0,27%
2101 2017-08-17      1288.01     1283.61     1290.47    1282.20        0,38%
2102 2017-08-16      1283.10     1271.87     1284.29    1268.19        0,86%

[2103 rows x 6 columns]

In [16]:
OHLC_XAUUSD[["XAUUSD-Close", "XAUUSD-Open", "XAUUSD-High", "XAUUSD-Low"]] = OHLC_XAUUSD[["XAUUSD-Close", "XAUUSD-Open", "XAUUSD-High", "XAUUSD-Low"]].astype(float)
OHLC_XAUUSD.dtypes

Date            datetime64[ns]
XAUUSD-Close           float64
XAUUSD-Open            float64
XAUUSD-High            float64
XAUUSD-Low             float64
XAUUSD-% var            object
dtype: object

In [17]:
OHLC_XAUUSD

,Date,XAUUSD-Close,XAUUSD-Open,XAUUSD-High,XAUUSD-Low,XAUUSD-% var
0,2025-09-16,3694.63,3677.29,3699.57,3674.79,"0,48%"
1,2025-09-15,3676.97,3644.40,3685.65,3626.60,"1,06%"
2,2025-09-14,3638.26,3644.79,3646.19,3636.92,"-0,13%"
3,2025-09-12,3643.13,3635.01,3656.86,3630.48,"0,25%"
4,2025-09-11,3634.09,3642.60,3649.27,3614.01,"-0,18%"
...,...,...,...,...,...,...
2098,2017-08-22,1284.72,1291.18,1292.69,1282.11,"-0,50%"
2099,2017-08-21,1291.22,1283.60,1293.58,1280.60,"0,52%"
2100,2017-08-18,1284.50,1288.20,1301.20,1283.64,"-0,27%"
2101,2017-08-17,1288.01,1283.61,1290.47,1282.20,"0,38%"
2102,2017-08-16,1283.10,1271.87,1284.29,1268.19,"0,86%"